version: '3.8'

services:
  # React Frontend Service
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app_network

  # Backend API Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8080:8080"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

